# Generated by Django 2.2.6 on 2019-10-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurios', '0002_auto_20191014_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinosaurio',
            name='imagen',
            field=models.ImageField(upload_to='dinos', verbose_name='Imágen'),
        ),
    ]
