# Generated by Django 2.2.6 on 2019-10-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurios', '0004_auto_20191016_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinosaurio',
            name='imagen',
            field=models.ImageField(upload_to='dinos', verbose_name='Imágen'),
        ),
    ]
