# Generated by Django 2.2.6 on 2019-11-26 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dinosaurios', '0006_auto_20191028_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotacionDino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(default=0, verbose_name='Calificación')),
                ('rollo', models.TextField(verbose_name='Reseña')),
                ('dinosaurio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dinosaurio', to='dinosaurios.Dinosaurio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
