# Generated by Django 2.2.6 on 2019-11-26 04:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dinosaurios', '0007_votaciondino'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VotacionDino',
            new_name='Votacion',
        ),
    ]
