# Generated by Django 2.2.6 on 2019-11-26 05:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaurios', '0009_auto_20191126_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votaciondino',
            name='calificacion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5, 'El valor máximo permitido es 5'), django.core.validators.MinValueValidator(1, 'El valor mínimo es 1')], verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='votaciondino',
            name='dinosaurio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinosaurios.Dinosaurio', verbose_name='Dinosaurio'),
        ),
    ]
