# Generated by Django 2.2.6 on 2019-11-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios', verbose_name='Foto'),
        ),
    ]
